In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ecommerce_estatistica.csv')

In [3]:
df.shape

(295, 24)

In [4]:
df.dtypes

Unnamed: 0               int64
Título                     str
Nota                   float64
N_Avaliações           float64
Desconto               float64
Marca                      str
Material                   str
Gênero                     str
Temporada                  str
Review1                    str
Review2                    str
Review3                    str
Qtd_Vendidos               str
Preço                  float64
Nota_MinMax            float64
N_Avaliações_MinMax    float64
Desconto_MinMax        float64
Preço_MinMax           float64
Marca_Cod                int64
Material_Cod             int64
Temporada_Cod            int64
Qtd_Vendidos_Cod       float64
Marca_Freq             float64
Material_Freq          float64
dtype: object

In [5]:
df.isnull().sum() / len(df)

Unnamed: 0             0.0
Título                 0.0
Nota                   0.0
N_Avaliações           0.0
Desconto               0.0
Marca                  0.0
Material               0.0
Gênero                 0.0
Temporada              0.0
Review1                0.0
Review2                0.0
Review3                0.0
Qtd_Vendidos           0.0
Preço                  0.0
Nota_MinMax            0.0
N_Avaliações_MinMax    0.0
Desconto_MinMax        0.0
Preço_MinMax           0.0
Marca_Cod              0.0
Material_Cod           0.0
Temporada_Cod          0.0
Qtd_Vendidos_Cod       0.0
Marca_Freq             0.0
Material_Freq          0.0
dtype: float64

In [6]:
df['Gênero'].unique()

<StringArray>
[                        'Masculino',                          'Feminino',
               'Sem gênero infantil',                        'Sem gênero',
                           'Meninos',                           'Meninas',
                           'Unissex',                             'Bebês',
 'roupa para gordinha pluss P ao 52']
Length: 9, dtype: str

In [7]:
df['Temporada'].unique()

<StringArray>
[                  'outono/inverno',                     'não definido',
                  'primavera/verão',   'primavera-verão outono-inverno',
                             '2021', 'primavera-verão - outono-inverno',
   'primavera/verão/outono/inverno']
Length: 7, dtype: str

In [8]:
df[df['Temporada'] == '2021'] # serão removidos

,Unnamed: 0,Título,Nota,N_Avaliações,Desconto,Marca,Material,Gênero,Temporada,Review1,...,Nota_MinMax,N_Avaliações_MinMax,Desconto_MinMax,Preço_MinMax,Marca_Cod,Material_Cod,Temporada_Cod,Qtd_Vendidos_Cod,Marca_Freq,Material_Freq
69,380,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,619.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068092,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638
79,432,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,619.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068092,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638
136,865,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,621.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068312,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638
140,917,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,621.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068312,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638
190,1345,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,621.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068312,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638
196,1397,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,621.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068312,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638
252,1831,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,621.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068312,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638
255,1883,Kit 10 Cuecas Lupo Boxer Masculinas Atacado Bo...,4.2,621.0,5.0,lupo,algodão 95%,Masculino,2021,"Horrível, não são originais, tecido áspero, ta...",...,0.703704,0.068312,0.0,0.288223,463,27,0,1000.0,0.042292,0.003638

In [9]:
df.drop(index=[69, 79, 136, 140, 190, 196, 252, 255], inplace=True)

In [10]:
df['sazonalidade'] = df['Temporada'].replace({"outono/inverno":"6 meses menor temperatura",
                                               "primavera/verão":"6 meses maior temperatura",
                                               "não definido":"demanda regular",
                                               "primavera-verão outono-inverno":"alta frequência",
                                               "primavera-verão - outono-inverno":"alta frequência"})

In [11]:
df[df['Temporada'] == "2021"]

Empty DataFrame
Columns: [Unnamed: 0, Título, Nota, N_Avaliações, Desconto, Marca, Material, Gênero, Temporada, Review1, Review2, Review3, Qtd_Vendidos, Preço, Nota_MinMax, N_Avaliações_MinMax, Desconto_MinMax, Preço_MinMax, Marca_Cod, Material_Cod, Temporada_Cod, Qtd_Vendidos_Cod, Marca_Freq, Material_Freq, sazonalidade]
Index: []

[0 rows x 25 columns]

In [12]:
df.head()

,Unnamed: 0,Título,Nota,N_Avaliações,Desconto,Marca,Material,Gênero,Temporada,Review1,...,N_Avaliações_MinMax,Desconto_MinMax,Preço_MinMax,Marca_Cod,Material_Cod,Temporada_Cod,Qtd_Vendidos_Cod,Marca_Freq,Material_Freq,sazonalidade
0,1,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034.0,18.0,lupo,algodão,Masculino,outono/inverno,As cuecas são boas; porém você percebe na cost...,...,0.334178,0.213115,0.378585,463,25,3,10000.0,0.042292,0.176444,6 meses menor temperatura
1,2,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682.0,20.0,zorba,algodão,Masculino,não definido,O tecido é bom e são confortáveis. Só que a nu...,...,0.625937,0.245902,0.322329,838,25,1,50000.0,0.009095,0.176444,demanda regular
2,3,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,4.6,1700.0,22.0,mash,algodão,Masculino,primavera/verão,"As cuecas são boas, porém meu marido usa g e p...",...,0.187197,0.278689,0.372617,494,25,7,10000.0,0.010914,0.176444,6 meses maior temperatura
3,4,Kit 3 Short Jeans Feminino Cintura Alta Barato...,4.4,507.0,9.0,menina linda,jean,Feminino,primavera/verão,Estou encantada com essas peças!.\nOs shorts s...,...,0.055751,0.065574,0.201767,509,74,7,1000.0,0.010005,0.025466,6 meses maior temperatura
4,5,Blusa + Calça Térmica Treino Futebol Criança I...,4.7,58.0,5.0,roupa zero grau,termico unissex,Sem gênero infantil,outono/inverno,"Produto ótimo , mesmo após várias lavagens não...",...,0.006280,0.000000,0.114508,669,166,3,100.0,0.002274,0.000910,6 meses menor temperatura

In [13]:
df.drop(columns=["Nota_MinMax", "N_Avaliações_MinMax", "Desconto_MinMax", "Preço_MinMax",
                 "Temporada_Cod", "Qtd_Vendidos_Cod", "Marca_Freq", "Review1", "Review2", "Review3",
                 "Temporada", "Material_Freq"], inplace=True)

In [14]:
df.dtypes

Unnamed: 0        int64
Título              str
Nota            float64
N_Avaliações    float64
Desconto        float64
Marca               str
Material            str
Gênero              str
Qtd_Vendidos        str
Preço           float64
Marca_Cod         int64
Material_Cod      int64
sazonalidade        str
dtype: object

In [15]:
df.head()

,Unnamed: 0,Título,Nota,N_Avaliações,Desconto,Marca,Material,Gênero,Qtd_Vendidos,Preço,Marca_Cod,Material_Cod,sazonalidade
0,1,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034.0,18.0,lupo,algodão,Masculino,+10mil,232.89,463,25,6 meses menor temperatura
1,2,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682.0,20.0,zorba,algodão,Masculino,+50mil,199.90,838,25,demanda regular
2,3,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,4.6,1700.0,22.0,mash,algodão,Masculino,+10mil,229.39,494,25,6 meses maior temperatura
3,4,Kit 3 Short Jeans Feminino Cintura Alta Barato...,4.4,507.0,9.0,menina linda,jean,Feminino,+1000,129.20,509,74,6 meses maior temperatura
4,5,Blusa + Calça Térmica Treino Futebol Criança I...,4.7,58.0,5.0,roupa zero grau,termico unissex,Sem gênero infantil,+100,78.03,669,166,6 meses menor temperatura

In [16]:
df.drop(columns=["Unnamed: 0", "Marca_Cod", "Material_Cod"], inplace=True)

In [17]:
df.head()

,Título,Nota,N_Avaliações,Desconto,Marca,Material,Gênero,Qtd_Vendidos,Preço,sazonalidade
0,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034.0,18.0,lupo,algodão,Masculino,+10mil,232.89,6 meses menor temperatura
1,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682.0,20.0,zorba,algodão,Masculino,+50mil,199.90,demanda regular
2,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,4.6,1700.0,22.0,mash,algodão,Masculino,+10mil,229.39,6 meses maior temperatura
3,Kit 3 Short Jeans Feminino Cintura Alta Barato...,4.4,507.0,9.0,menina linda,jean,Feminino,+1000,129.20,6 meses maior temperatura
4,Blusa + Calça Térmica Treino Futebol Criança I...,4.7,58.0,5.0,roupa zero grau,termico unissex,Sem gênero infantil,+100,78.03,6 meses menor temperatura

In [18]:
df.rename(columns={"Título":"produto", "Nota":"nota", "N_Avaliações":"avaliacoes",
                   "Desconto":"desconto", "Marca":"marca", "Material":"material",
                   "Gênero":"publico_voltado", "Qtd_Vendidos":"qtd_vendidos", "Preço":"preco",}, inplace=True)

In [19]:
df.head()

,produto,nota,avaliacoes,desconto,marca,material,publico_voltado,qtd_vendidos,preco,sazonalidade
0,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034.0,18.0,lupo,algodão,Masculino,+10mil,232.89,6 meses menor temperatura
1,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682.0,20.0,zorba,algodão,Masculino,+50mil,199.90,demanda regular
2,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,4.6,1700.0,22.0,mash,algodão,Masculino,+10mil,229.39,6 meses maior temperatura
3,Kit 3 Short Jeans Feminino Cintura Alta Barato...,4.4,507.0,9.0,menina linda,jean,Feminino,+1000,129.20,6 meses maior temperatura
4,Blusa + Calça Térmica Treino Futebol Criança I...,4.7,58.0,5.0,roupa zero grau,termico unissex,Sem gênero infantil,+100,78.03,6 meses menor temperatura

In [20]:
df['publico_voltado'].unique()

<StringArray>
[                        'Masculino',                          'Feminino',
               'Sem gênero infantil',                        'Sem gênero',
                           'Meninos',                           'Meninas',
                           'Unissex',                             'Bebês',
 'roupa para gordinha pluss P ao 52']
Length: 9, dtype: str

In [21]:
df['publico_voltado'] = df['publico_voltado'].replace({"Sem gênero":"Unissex", "Meninos":"Infantil:masculino",
                                                       "Meninas":"Infantil:feminino", "Sem gênero infantil":"infantil:Unissex"})

In [22]:
df['publico_voltado'].unique()

<StringArray>
[                        'Masculino',                          'Feminino',
                  'infantil:Unissex',                           'Unissex',
                'Infantil:masculino',                 'Infantil:feminino',
                             'Bebês', 'roupa para gordinha pluss P ao 52']
Length: 8, dtype: str

In [23]:
df['avaliacoes'] = df['avaliacoes'].astype(int)

In [24]:
df['desconto'] = df['desconto'].astype(int)

In [25]:
df.head(2)

,produto,nota,avaliacoes,desconto,marca,material,publico_voltado,qtd_vendidos,preco,sazonalidade
0,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034,18,lupo,algodão,Masculino,+10mil,232.89,6 meses menor temperatura
1,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682,20,zorba,algodão,Masculino,+50mil,199.90,demanda regular

In [26]:
df['qtd_vendidos'].unique()

<StringArray>
['+10mil', '+50mil', '+1000', '+100', '+50', '+5', '+25']
Length: 7, dtype: str

In [27]:
df['qtd_vendido_int'] = df['qtd_vendidos'].replace({"+5":5, "+25":25, "+50":50, "+100":100,
                                                    "+1000":1000,"+10mil":10000, "+50mil":50000})

In [28]:
df['preco_desconto'] =  round(df['preco'] - (df['preco'] * df['desconto'] / 100), 2)

In [29]:
df.drop(columns=['qtd_vendidos'], inplace=True)

In [30]:
df = df.rename(columns={"qtd_vendido_int":"qtd_vendidos"})

In [31]:
df.head()

,produto,nota,avaliacoes,desconto,marca,material,publico_voltado,preco,sazonalidade,qtd_vendidos,preco_desconto
0,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034,18,lupo,algodão,Masculino,232.89,6 meses menor temperatura,10000,190.97
1,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682,20,zorba,algodão,Masculino,199.90,demanda regular,50000,159.92
2,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,4.6,1700,22,mash,algodão,Masculino,229.39,6 meses maior temperatura,10000,178.92
3,Kit 3 Short Jeans Feminino Cintura Alta Barato...,4.4,507,9,menina linda,jean,Feminino,129.20,6 meses maior temperatura,1000,117.57
4,Blusa + Calça Térmica Treino Futebol Criança I...,4.7,58,5,roupa zero grau,termico unissex,infantil:Unissex,78.03,6 meses menor temperatura,100,74.13

In [32]:
# ordenando variáveis

ordem = ['produto', 'marca', 'material', 'preco', 'desconto', 'preco_desconto', 'publico_voltado', 'nota', 'avaliacoes', 'qtd_vendidos', 'sazonalidade']

In [33]:
df = df[ordem]

In [34]:
df.head()

,produto,marca,material,preco,desconto,preco_desconto,publico_voltado,nota,avaliacoes,qtd_vendidos,sazonalidade
0,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,lupo,algodão,232.89,18,190.97,Masculino,4.5,3034,10000,6 meses menor temperatura
1,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,zorba,algodão,199.90,20,159.92,Masculino,4.7,5682,50000,demanda regular
2,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,mash,algodão,229.39,22,178.92,Masculino,4.6,1700,10000,6 meses maior temperatura
3,Kit 3 Short Jeans Feminino Cintura Alta Barato...,menina linda,jean,129.20,9,117.57,Feminino,4.4,507,1000,6 meses maior temperatura
4,Blusa + Calça Térmica Treino Futebol Criança I...,roupa zero grau,termico unissex,78.03,5,74.13,infantil:Unissex,4.7,58,100,6 meses menor temperatura

In [35]:
df.to_csv('ecommerce_estatistica_V1.csv', index=False)